QT = core

CONFIG += c++17 cmdline

# You can make your code fail to compile if it uses deprecated APIs.
# In order to do so, uncomment the following line.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0

SOURCES += \
        src/CControl/Sources/ArtificialIntelligence/Astar.c \
        src/CControl/Sources/ArtificialIntelligence/inpolygon.c \
        src/CControl/Sources/ComputerVision/cornerdetection.c \
        src/CControl/Sources/ComputerVision/featuredetection.c \
        src/CControl/Sources/ComputerVision/fisherfaces.c \
        src/CControl/Sources/ComputerVision/generalizedhough.c \
        src/CControl/Sources/ComputerVision/hough.c \
        src/CControl/Sources/ComputerVision/violajones.c \
        src/CControl/Sources/ControlEngineering/c2d.c \
        src/CControl/Sources/ControlEngineering/cab.c \
        src/CControl/Sources/ControlEngineering/obsv.c \
        src/CControl/Sources/ControlEngineering/qmpc.c \
        src/CControl/Sources/ControlEngineering/ssint.c \
        src/CControl/Sources/ControlEngineering/stability.c \
        src/CControl/Sources/Hardware/concatenate_paths.c \
        src/CControl/Sources/Hardware/count_sub_folders.c \
        src/CControl/Sources/Hardware/detectmemoryleak.c \
        src/CControl/Sources/Hardware/saveload.c \
        src/CControl/Sources/Hardware/scan_file_names.c \
        src/CControl/Sources/Hardware/scan_sub_folder_names.c \
        src/CControl/Sources/ImageProcessing/fspecial.c \
        src/CControl/Sources/ImageProcessing/haarlike.c \
        src/CControl/Sources/ImageProcessing/harris.c \
        src/CControl/Sources/ImageProcessing/imcollect.c \
        src/CControl/Sources/ImageProcessing/imfree.c \
        src/CControl/Sources/ImageProcessing/imgaussfilt.c \
        src/CControl/Sources/ImageProcessing/imread.c \
        src/CControl/Sources/ImageProcessing/imresize.c \
        src/CControl/Sources/ImageProcessing/imshow.c \
        src/CControl/Sources/ImageProcessing/imwrite.c \
        src/CControl/Sources/ImageProcessing/integralimage.c \
        src/CControl/Sources/ImageProcessing/intensitycentroid.c \
        src/CControl/Sources/ImageProcessing/lbp.c \
        src/CControl/Sources/ImageProcessing/pooling.c \
        src/CControl/Sources/ImageProcessing/rpca.c \
        src/CControl/Sources/ImageProcessing/sobel.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Routines/ieeeck.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Routines/iladlc.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Routines/iladlr.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Routines/ilaenv.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Routines/ilaslc.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Routines/ilaslr.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Routines/iparmq.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Routines/isamax.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Routines/lsame.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Routines/saxpy.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Routines/sbdsdc.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Routines/sbdsqr.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Routines/sceil.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Routines/scopy.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Routines/sdot.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Routines/sgebak.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Routines/sgebal.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Routines/sgebd2.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Routines/sgebrd.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Routines/sgeev.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Routines/sgehd2.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Routines/sgehrd.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Routines/sgelq2.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Routines/sgelqf.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Routines/sgemm.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Routines/sgemv.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Routines/sgeqr2.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Routines/sgeqrf.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Routines/sger.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Routines/sgesdd.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Routines/sgesvd.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Routines/sgetrf.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Routines/sgetri.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Routines/sgetrs.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Routines/sggbak.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Routines/sggbal.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Routines/sggev.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Routines/sgghrd.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Routines/shgeqz.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Routines/shseqr.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Routines/sisnan.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Routines/slabad.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Routines/slabrd.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Routines/slacpy.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Routines/sladiv.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Routines/slae2.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Routines/slaed0.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Routines/slaed1.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Routines/slaed2.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Routines/slaed3.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Routines/slaed4.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Routines/slaed5.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Routines/slaed6.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Routines/slaed7.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Routines/slaed8.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Routines/slaed9.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Routines/slaeda.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Routines/slaev2.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Routines/slaexc.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Routines/slag2.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Routines/slahqr.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Routines/slahr2.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Routines/slaisnan.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Routines/slaln2.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Routines/slamch.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Routines/slamrg.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Routines/slange.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Routines/slanhs.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Routines/slanst.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Routines/slansy.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Routines/slanv2.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Routines/slapy2.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Routines/slapy3.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Routines/slaqr0.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Routines/slaqr1.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Routines/slaqr2.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Routines/slaqr3.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Routines/slaqr4.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Routines/slaqr5.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Routines/slarf.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Routines/slarfb.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Routines/slarfg.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Routines/slarfp.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Routines/slarft.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Routines/slarfx.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Routines/slartg.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Routines/slas2.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Routines/slascl.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Routines/slasd0.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Routines/slasd1.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Routines/slasd2.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Routines/slasd3.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Routines/slasd4.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Routines/slasd5.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Routines/slasd6.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Routines/slasd7.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Routines/slasd8.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Routines/slasda.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Routines/slasdq.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Routines/slasdt.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Routines/slaset.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Routines/slasq1.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Routines/slasq2.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Routines/slasq3.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Routines/slasq4.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Routines/slasq5.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Routines/slasq6.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Routines/slasr.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Routines/slasrt.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Routines/slassq.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Routines/slasv2.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Routines/slaswp.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Routines/slasy2.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Routines/slatrd.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Routines/snrm2.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Routines/sorg2r.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Routines/sorgbr.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Routines/sorghr.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Routines/sorgl2.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Routines/sorglq.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Routines/sorgqr.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Routines/sorm2l.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Routines/sorm2r.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Routines/sormbr.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Routines/sormhr.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Routines/sorml2.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Routines/sormlq.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Routines/sormql.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Routines/sormqr.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Routines/sormtr.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Routines/sposv.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Routines/spotf2.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Routines/spotrf.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Routines/spotrs.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Routines/srot.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Routines/sscal.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Routines/sstedc.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Routines/ssteqr.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Routines/ssterf.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Routines/sswap.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Routines/ssyevd.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Routines/ssygs2.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Routines/ssygst.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Routines/ssygvd.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Routines/ssymm.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Routines/ssymv.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Routines/ssyr2.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Routines/ssyr2k.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Routines/ssyrk.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Routines/ssytd2.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Routines/ssytrd.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Routines/stgevc.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Routines/strevc.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Routines/strexc.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Routines/strmm.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Routines/strmv.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Routines/strsm.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Routines/strsv.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Routines/strti2.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Routines/strtri.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Routines/xerbla.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Tools/close.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Tools/endfile.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Tools/err.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Tools/exit_.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Tools/f77_aloc.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Tools/fmt.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Tools/fmtlib.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Tools/i_len_trim.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Tools/i_nint.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Tools/open.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Tools/pow_dd.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Tools/pow_ii.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Tools/pow_ri.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Tools/r_lg10.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Tools/r_sign.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Tools/s_cat.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Tools/s_cmp.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Tools/s_copy.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Tools/s_stop.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Tools/sfe.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Tools/sig_die.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Tools/util.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Tools/wref.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Tools/wrtfmt.c \
        src/CControl/Sources/LinearAlgebra/CLapack/Tools/wsfe.c \
        src/CControl/Sources/LinearAlgebra/balance.c \
        src/CControl/Sources/LinearAlgebra/chol.c \
        src/CControl/Sources/LinearAlgebra/cholupdate.c \
        src/CControl/Sources/LinearAlgebra/conv.c \
        src/CControl/Sources/LinearAlgebra/conv2.c \
        src/CControl/Sources/LinearAlgebra/conv2fft.c \
        src/CControl/Sources/LinearAlgebra/convfft.c \
        src/CControl/Sources/LinearAlgebra/det.c \
        src/CControl/Sources/LinearAlgebra/dlyap.c \
        src/CControl/Sources/LinearAlgebra/dot.c \
        src/CControl/Sources/LinearAlgebra/eig.c \
        src/CControl/Sources/LinearAlgebra/eig_generalized.c \
        src/CControl/Sources/LinearAlgebra/expm.c \
        src/CControl/Sources/LinearAlgebra/hankel.c \
        src/CControl/Sources/LinearAlgebra/inv.c \
        src/CControl/Sources/LinearAlgebra/linsolve_chol.c \
        src/CControl/Sources/LinearAlgebra/linsolve_gauss.c \
        src/CControl/Sources/LinearAlgebra/linsolve_lower_triangular.c \
        src/CControl/Sources/LinearAlgebra/linsolve_lup.c \
        src/CControl/Sources/LinearAlgebra/linsolve_qr.c \
        src/CControl/Sources/LinearAlgebra/linsolve_upper_triangular.c \
        src/CControl/Sources/LinearAlgebra/lup.c \
        src/CControl/Sources/LinearAlgebra/mul.c \
        src/CControl/Sources/LinearAlgebra/nonlinsolve.c \
        src/CControl/Sources/LinearAlgebra/norm.c \
        src/CControl/Sources/LinearAlgebra/pinv.c \
        src/CControl/Sources/LinearAlgebra/qr.c \
        src/CControl/Sources/LinearAlgebra/rank.c \
        src/CControl/Sources/LinearAlgebra/svd.c \
        src/CControl/Sources/LinearAlgebra/tran.c \
        src/CControl/Sources/MachineLearning/adaboost.c \
        src/CControl/Sources/MachineLearning/dbscan.c \
        src/CControl/Sources/MachineLearning/kernel.c \
        src/CControl/Sources/MachineLearning/kmeans.c \
        src/CControl/Sources/MachineLearning/kpca.c \
        src/CControl/Sources/MachineLearning/kpca_lda_nn.c \
        src/CControl/Sources/MachineLearning/nn.c \
        src/CControl/Sources/MachineLearning/svm.c \
        src/CControl/Sources/Miscellaneous/anglevector.c \
        src/CControl/Sources/Miscellaneous/cat.c \
        src/CControl/Sources/Miscellaneous/cumsum.c \
        src/CControl/Sources/Miscellaneous/cut.c \
        src/CControl/Sources/Miscellaneous/deg2rad.c \
        src/CControl/Sources/Miscellaneous/find.c \
        src/CControl/Sources/Miscellaneous/float2uint.c \
        src/CControl/Sources/Miscellaneous/ind2sub.c \
        src/CControl/Sources/Miscellaneous/insert.c \
        src/CControl/Sources/Miscellaneous/issymmetric.c \
        src/CControl/Sources/Miscellaneous/normalize.c \
        src/CControl/Sources/Miscellaneous/pdist2.c \
        src/CControl/Sources/Miscellaneous/popcount.c \
        src/CControl/Sources/Miscellaneous/print.c \
        src/CControl/Sources/Miscellaneous/rad2deg.c \
        src/CControl/Sources/Miscellaneous/radianvector.c \
        src/CControl/Sources/Miscellaneous/rot2d.c \
        src/CControl/Sources/Miscellaneous/saturation.c \
        src/CControl/Sources/Miscellaneous/scalar.c \
        src/CControl/Sources/Miscellaneous/shuffle.c \
        src/CControl/Sources/Miscellaneous/sign.c \
        src/CControl/Sources/Miscellaneous/sort.c \
        src/CControl/Sources/Miscellaneous/sum.c \
        src/CControl/Sources/Miscellaneous/uint2float.c \
        src/CControl/Sources/Miscellaneous/unique.c \
        src/CControl/Sources/Miscellaneous/unit.c \
        src/CControl/Sources/Miscellaneous/vmax.c \
        src/CControl/Sources/Miscellaneous/vmin.c \
        src/CControl/Sources/Optimization/linprog.c \
        src/CControl/Sources/Optimization/lsqnonneg.c \
        src/CControl/Sources/Optimization/quadprog.c \
        src/CControl/Sources/SignalProcessing/FFTpack/fftpack.c \
        src/CControl/Sources/SignalProcessing/clusterfilter.c \
        src/CControl/Sources/SignalProcessing/fft.c \
        src/CControl/Sources/SignalProcessing/fft2.c \
        src/CControl/Sources/SignalProcessing/fftshift.c \
        src/CControl/Sources/SignalProcessing/filtfilt.c \
        src/CControl/Sources/SignalProcessing/ifft.c \
        src/CControl/Sources/SignalProcessing/ifft2.c \
        src/CControl/Sources/SignalProcessing/ifftshift.c \
        src/CControl/Sources/SignalProcessing/pf.c \
        src/CControl/Sources/SignalProcessing/sr_ukf_state_estimation.c \
        src/CControl/Sources/Statistics/amax.c \
        src/CControl/Sources/Statistics/amin.c \
        src/CControl/Sources/Statistics/area.c \
        src/CControl/Sources/Statistics/center.c \
        src/CControl/Sources/Statistics/centroid.c \
        src/CControl/Sources/Statistics/clusterratio.c \
        src/CControl/Sources/Statistics/clustersdistance.c \
        src/CControl/Sources/Statistics/cov.c \
        src/CControl/Sources/Statistics/covm.c \
        src/CControl/Sources/Statistics/giniimpurity.c \
        src/CControl/Sources/Statistics/lda.c \
        src/CControl/Sources/Statistics/mean.c \
        src/CControl/Sources/Statistics/normpdf.c \
        src/CControl/Sources/Statistics/opa.c \
        src/CControl/Sources/Statistics/pca.c \
        src/CControl/Sources/Statistics/randi.c \
        src/CControl/Sources/Statistics/randn.c \
        src/CControl/Sources/Statistics/randperm.c \
        src/CControl/Sources/Statistics/stddev.c \
        src/CControl/Sources/Statistics/var.c \
        src/CControl/Sources/SystemIdentification/era.c \
        src/CControl/Sources/SystemIdentification/okid.c \
        src/CControl/Sources/SystemIdentification/rls.c \
        src/CControl/Sources/SystemIdentification/sr_ukf_parameter_estimation.c \
        src/CControl/Sources/SystemIdentification/theta2ss.c \
        src\main.c

# Default rules for deployment.
qnx: target.path = /tmp/$${TARGET}/bin
else: unix:!android: target.path = /opt/$${TARGET}/bin
!isEmpty(target.path): INSTALLS += target

HEADERS += \
    src/CControl/Headers/defines.h \
    src/CControl/Headers/enums.h \
    src/CControl/Headers/functions.h \
    src/CControl/Headers/headers.h \
    src/CControl/Headers/macros.h \
    src/CControl/Headers/structs.h \
    src/CControl/Headers/unions.h \
    src/CControl/Sources/ArtificialIntelligence/artificialintelligence.h \
    src/CControl/Sources/ComputerVision/computervision.h \
    src/CControl/Sources/ControlEngineering/controlengineering.h \
    src/CControl/Sources/Hardware/hardware.h \
    src/CControl/Sources/ImageProcessing/imageprocessing.h \
    src/CControl/Sources/LinearAlgebra/CLapack/Routines/blaswrap.h \
    src/CControl/Sources/LinearAlgebra/CLapack/Routines/clapack.h \
    src/CControl/Sources/LinearAlgebra/CLapack/Routines/f2c.h \
    src/CControl/Sources/LinearAlgebra/CLapack/Routines/routines.h \
    src/CControl/Sources/LinearAlgebra/CLapack/Tools/f2c.h \
    src/CControl/Sources/LinearAlgebra/CLapack/Tools/fio.h \
    src/CControl/Sources/LinearAlgebra/CLapack/Tools/fmt.h \
    src/CControl/Sources/LinearAlgebra/CLapack/Tools/fp.h \
    src/CControl/Sources/LinearAlgebra/CLapack/Tools/sysdep1.h \
    src/CControl/Sources/LinearAlgebra/CLapack/Tools/tools.h \
    src/CControl/Sources/LinearAlgebra/CLapack/clapack.h \
    src/CControl/Sources/LinearAlgebra/linearalgebra.h \
    src/CControl/Sources/MachineLearning/machinelearning.h \
    src/CControl/Sources/Miscellaneous/miscellaneous.h \
    src/CControl/Sources/Optimization/optimization.h \
    src/CControl/Sources/SignalProcessing/FFTpack/fftpack.h \
    src/CControl/Sources/SignalProcessing/signalprocessing.h \
    src/CControl/Sources/Statistics/statistics.h \
    src/CControl/Sources/SystemIdentification/systemidentification.h \
    src/CControl/Sources/sources.h \
    src/CControl/ccontrol.h
