// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.220531.1

#pragma once
#ifndef WINRT_Windows_UI_Input_Preview_Text_1_H
#define WINRT_Windows_UI_Input_Preview_Text_1_H
#include "winrt/impl/Windows.UI.Input.Preview.Text.0.h"
WINRT_EXPORT namespace winrt::Windows::UI::Input::Preview::Text
{
    struct __declspec(empty_bases) IConversionModeChangedEventArgs :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IConversionModeChangedEventArgs>
    {
        IConversionModeChangedEventArgs(std::nullptr_t = nullptr) noexcept {}
        IConversionModeChangedEventArgs(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IFocusEnteredEventArgs :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IFocusEnteredEventArgs>
    {
        IFocusEnteredEventArgs(std::nullptr_t = nullptr) noexcept {}
        IFocusEnteredEventArgs(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IInputDelegationModeChangedEventArgs :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IInputDelegationModeChangedEventArgs>
    {
        IInputDelegationModeChangedEventArgs(std::nullptr_t = nullptr) noexcept {}
        IInputDelegationModeChangedEventArgs(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IKeyEventReceivedEventArgs :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IKeyEventReceivedEventArgs>
    {
        IKeyEventReceivedEventArgs(std::nullptr_t = nullptr) noexcept {}
        IKeyEventReceivedEventArgs(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IKeyboardInputProcessor :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IKeyboardInputProcessor>
    {
        IKeyboardInputProcessor(std::nullptr_t = nullptr) noexcept {}
        IKeyboardInputProcessor(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IReconversionRequestedEventArgs :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IReconversionRequestedEventArgs>
    {
        IReconversionRequestedEventArgs(std::nullptr_t = nullptr) noexcept {}
        IReconversionRequestedEventArgs(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) ITextBoxContentChangedEventArgs :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<ITextBoxContentChangedEventArgs>
    {
        ITextBoxContentChangedEventArgs(std::nullptr_t = nullptr) noexcept {}
        ITextBoxContentChangedEventArgs(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) ITextBoxInfo :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<ITextBoxInfo>
    {
        ITextBoxInfo(std::nullptr_t = nullptr) noexcept {}
        ITextBoxInfo(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) ITextBoxInfoChangedEventArgs :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<ITextBoxInfoChangedEventArgs>
    {
        ITextBoxInfoChangedEventArgs(std::nullptr_t = nullptr) noexcept {}
        ITextBoxInfoChangedEventArgs(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) ITextComposition :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<ITextComposition>
    {
        ITextComposition(std::nullptr_t = nullptr) noexcept {}
        ITextComposition(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) ITextCompositionSegment :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<ITextCompositionSegment>
    {
        ITextCompositionSegment(std::nullptr_t = nullptr) noexcept {}
        ITextCompositionSegment(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) ITextEditSession :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<ITextEditSession>
    {
        ITextEditSession(std::nullptr_t = nullptr) noexcept {}
        ITextEditSession(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) ITextInputProvider :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<ITextInputProvider>
    {
        ITextInputProvider(std::nullptr_t = nullptr) noexcept {}
        ITextInputProvider(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) ITextInputService :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<ITextInputService>
    {
        ITextInputService(std::nullptr_t = nullptr) noexcept {}
        ITextInputService(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) ITextInputServiceStatics :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<ITextInputServiceStatics>
    {
        ITextInputServiceStatics(std::nullptr_t = nullptr) noexcept {}
        ITextInputServiceStatics(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
}
#endif
