/*
 * Enums.h
 *
 *  Created on: 20 Juli. 2023
 *      Author: Daniel Mårtensson
 */

#ifndef CCONTROL_HEADERS_ENUMS_H_
#define CCONTROL_HEADERS_ENUMS_H_

 /* For lqi.c */
typedef enum {
	ANTI_WINUP_ALWAYS_INTEGRATE,
	ANTI_WINUP_ONLY_INTEGRATE_WHEN_R_GRATER_THAN_Y_ELSE_DELETE,
	ANTI_WINUP_ONLY_INTEGRATE_WHEN_R_Y
}ANTI_WINUP;

/* For norm.c */
typedef enum {
	NORM_METHOD_L1,
	NORM_METHOD_L2,
	NORM_METHOD_FROBENIUS
}NORM_METHOD;

/* For sort.c */
typedef enum {
	SORT_MODE_ROW_DIRECTION_ASCEND,
	SORT_MODE_ROW_DIRECTION_DESCEND,
	SORT_MODE_COLUMN_DIRECTION_ASCEND,
	SORT_MODE_COLUMN_DIRECTION_DESCEND,
}SORT_MODE;

/* For Astar.c */
typedef enum {
	ASTAR_MODE_L1,
	ASTAR_MODE_L2
}ASTAR_MODE;

/* For pdist2.c */
typedef enum {
	PDIST2_METRIC_SQEUCLIDEAN,
	PDIST2_METRIC_L1,
	PDIST2_METRIC_L2,
	PDIST2_METRIC_COSINE,
	PDIST2_METRIC_EMD,
	PDIST2_METRIC_CHISQUARE
}PDIST2_METRIC;

/* For find.c */
typedef enum {
	FIND_CONDITION_METOD_E,
	FIND_CONDITION_METOD_GE,
	FIND_CONDITION_METOD_G,
	FIND_CONDITION_METOD_LE,
	FIND_CONDITION_METOD_L
}FIND_CONDITION_METOD;

/* For pooling.c */
typedef enum {
	POOLING_METOD_MAX,
	POOLING_METOD_AVERAGE,
	POOLING_METHOD_SHAPE
}POOLING_METOD;

#endif // !CCONTROL_HEADERS_ENUMS_H_
